-- 2021에 출판된 인문 카테고리의 도서 리스트 반환
SELECT BOOK_ID, PUBLISHED_DATE
    FROM BOOK
    WHERE 
    -- YEAR(PUBLISHED_DATE = 2021
    PUBLISHED_DATE LIKE '2021-%'
    AND
    CATEGORY = '인문'
    ORDER BY PUBLISHED_DATE ASC;